Make imports robust for building docs
The original import broke `make html` in my setup:
  File ".../horovod/common/basics.py", line 19, in <module>
    import horovod.common.util as util
  AttributeError: module 'horovod.common' has no attribute 'util'

Signed-off-by: Enrico Minack <github@enrico.minack.dev>