Pin numpy<2 as Keras is built against Numpy 1.x
Fixes issues like

    ...
      File "/venv/lib/python3.9/site-packages/keras/src/trainers/data_adapters/array_slicing.py", line 12, in <module>
        import pandas
      File "/venv/lib/python3.9/site-packages/pandas/__init__.py", line 26, in <module>
        from pandas.compat import (
      File "/venv/lib/python3.9/site-packages/pandas/compat/__init__.py", line 27, in <module>
        from pandas.compat.pyarrow import (
      File "/venv/lib/python3.9/site-packages/pandas/compat/pyarrow.py", line 8, in <module>
        import pyarrow as pa
      File "/venv/lib/python3.9/site-packages/pyarrow/__init__.py", line 65, in <module>
        import pyarrow.lib as _lib
    AttributeError: _ARRAY_API not found

    A module that was compiled using NumPy 1.x cannot be run in
    NumPy 2.0.2 as it may crash. To support both 1.x and 2.x
    versions of NumPy, modules must be compiled with NumPy 2.0.
    Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

    If you are a user of the module, the easiest solution will be to
    downgrade to 'numpy<2' or try to upgrade the affected module.
    We expect that some modules will need time to support NumPy 2.

Signed-off-by: Enrico Minack <github@enrico.minack.dev>